name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Working Directory
        run: |
          pwd

      - name: Print Python Version
        run: |
          python --version

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/SeleniumPythonUnitTest/SeleniumPythonUnitTest
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/SeleniumPythonUnitTest/SeleniumPythonUnitTest/pages


      - name: Print Current Directory Contents
        run: |
          ls -la

      - name: Run Selenium Tests
        run: python tests/test_login.py
